export const VALIDATE_RESOURCES_IDS = 'validate-resources-ids'

export const EMAIL_QUEUE = 'email_queue'
export const EMAIL_SERVICE = 'EMAIL_SERVICE'

export const SEND_PASSWORD_RESET = 'SEND_PASSWORD_RESET'

export const EMBEDDING_QUEUE = 'embedding_queue'
export const EMBEDDING_SERVICE = 'EMBEDDING_SERVICE'

export const GENERATE_TASK_EMBEDDING = 'GENERATE_TASK_EMBEDDING'
export const GENERATE_COMMENT_EMBEDDING = 'GENERATE_COMMENT_EMBEDDING'
export const GENERATE_PROJECT_EMBEDDING = 'GENERATE_PROJECT_EMBEDDING'

export const DELETE_EMBEDDING = 'DELETE_EMBEDDING'
export const DELETE_EMBEDDING_BY_PROJECT = 'DELETE_EMBEDDING_BY_PROJECT'
export const DELETE_TASK_EMBEDDING = 'DELETE_TASK_EMBEDDING'

export const GENERATE_ATTACHMENT_EMBEDDING = 'GENERATE_ATTACHMENT_EMBEDDING'
export const DELETE_ATTACHMENT_EMBEDDING = 'DELETE_ATTACHMENT_EMBEDDING'

export const CHAT_QUEUE = 'chat_queue'
export const CHAT_SERVICE = 'CHAT_SERVICE'
export const PROCESS_CHAT_MESSAGE = 'process_chat_message'

export const CHAT_STATUS_EVENT = 'chat:status'
export const WS_TICKET_PURPOSE = 'ws'
